#=================MAS3K=======================================
Net: vit_b
Test:
  batch_size: 1
  ckpt: best/MAS3K/20241111-141410/best_lora_96.pth 
  decoder: best/MAS3K/20241111-141410/best_other_96.pth        
  test_image_dir: data/MAS3K/test/Image/
  test_lbl_dir: data/MAS3K/test/Mask/
  test_size: 512
  testset_name: MAS3K

Train:
  batch_size: 4
  epoch_num: 200
  net: MAS3K
  optimizer_lr: 0.0001
  tra_image_dir: data/MAS3K/train/Image/
  tra_lbl_dir: data/MAS3K/train/Mask/
  train_size: 512

exp_name: Pytorch SP-SAM-B MAS3K
