#=================RMAS========================================
Net: vit_l
Test:
  batch_size: 1
  ckpt: best/RMAS/20241021-142948/best_lora_89.pth   
  decoder: best/RMAS/20241021-142948/best_other_89.pth
  test_image_dir: data/RMAS/test/img/
  test_lbl_dir: data/RMAS/test/label/
  test_size: 512
  testset_name: RMAS

Train:
  batch_size: 4
  epoch_num: 200
  net: RMAS
  optimizer_lr: 0.0001
  tra_image_dir: data/RMAS/train/img/
  tra_lbl_dir: data/RMAS/train/label/
  train_size: 512


exp_name: Pytorch SP-SAM-L RMAS
