#=================RMAS========================================
Net: vit_h
Test:
  batch_size: 1
  ckpt: best/RMAS/20241025-161429/best_lora_69.pth   
  decoder: best/RMAS/20241025-161429/best_other_69.pth
  test_image_dir: data/RMAS/test/img/
  test_lbl_dir: data/RMAS/test/label/
  test_size: 512
  testset_name: RMAS

Train:
  batch_size: 8
  epoch_num: 200
  net: RMAS
  optimizer_lr: 0.0001
  tra_image_dir: data/RMAS/train/img/
  tra_lbl_dir: data/RMAS/train/label/
  train_size: 512


exp_name: Pytorch SP-SAM-H RMAS
